import Head from 'next/head'
import { ConnectModal, ConnectWallet, Wallet } from '@xircus-web3/components'
import { Container } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ConnectModal>
          <Wallet />          
        </ConnectModal>
      </Container>
    </>
  )
}
